FROM tensorflow/tensorflow

RUN pip install keras
RUN pip install h5py
RUN pip install --upgrade jupyter

RUN useradd -ms /bin/bash Google-QuickDraw2-2.ipynb
WORKDIR /home/Google-QuickDraw2-2.ipynb

COPY data-download.sh .
RUN chown -R Google-QuickDraw2-2.ipynb .
RUN chmod +x ./data-download.sh
