version: '3.3'
services:
  quickdraw:
    build:
      context: .
      dockerfile: Dockerfile.train
    volumes:
      - ./Google-QuickDraw2-2.ipynb
      - ./data-download.sh
      - ./Google-QuickDraw2-2.ipynb
    ports:
      - 8888:8888
